### PR TITLE
Incorrect file name

### PR DESCRIPTION
**Pull request by marcelo-maciel**
Incorrect file name

### CODE REVIEW

**Comment by kant2002** [comment]
Here the actually correctly named name of the component, which by convention derived from name of CSHTML file. So I belive documentation is correct

**Comment by marcelo-maciel** [comment]
Then 'ConfiguredPizzaItem' is not a better option?

**Comment by kant2002** [comment]
Yes. You are right.

**Comment by marcelo-maciel** [comment]
Ok, adjusted.

**Pull request closed without merging**
